### ISSUE TITLE
Fix Broken Layout at Profile Field "Bio"

### ISSUE THREAD

**Issue by raianpollock** [playthecall/playthecall-2013#132]
![aboutmepagebreak](https://f.cloud.github.com/assets/3105616/28549/0361755c-4c4e-11e2-9e34-cd56c65cd6ff.JPG)

Guys, if the text in the field "bio" gets too big, it goes behind the content on the right.

**Comment by eniolopes** [comment]
@raulsouzalima @krawdyah

**Comment by raulsouzalima** [comment]
Fixed!

**Comment by raianpollock** [comment]
when i open the page this is what i see. i'm i the only one?

![ptcprofbug](https://f.cloud.github.com/assets/3105616/41097/28753bfa-55ca-11e2-8173-fcf0393a0b96.JPG)

**Comment by raianpollock** [comment]
the profile picture somehow dissapeared. i just uploaded a new one, but the pagebreak issue is still the same.
